"""Deterministic specialist logic for paper-comparison investigations.

Templates are filled only with values extracted from the papers or computed by the experiment;
support scores remain disclosed heuristics. No text is generated by a model.
"""

from backend.models import Experiment, Hypothesis
from backend.papers import topic_phrase


def _topic(analysis: dict) -> str:
    if analysis.get("topic"):
        return analysis["topic"]
    return topic_phrase(
        analysis["papers"][0]["meta"].get("title") or "",
        analysis.get("focus_terms") or [],
        (analysis.get("best_pair") or {}).get("shared_terms") or [],
    )


def _short(title: str, limit: int = 90) -> str:
    if len(title) <= limit:
        return title
    return title[:limit].rsplit(" ", 1)[0].rstrip(" ,:;") + "…"


def _top_difference(analysis: dict) -> dict | None:
    differences = analysis.get("condition_differences") or []
    return differences[0] if differences else None


def objective(analysis: dict) -> str:
    a, b = analysis["papers"]
    return (
        f"Why do “{_short(a['meta']['title'])}” and “{_short(b['meta']['title'])}” disagree about {_topic(analysis)}?"
    )


def hypotheses(analysis: dict) -> list[Hypothesis]:
    difference = _top_difference(analysis)
    context_field = difference["field"] if difference else "study context"
    context_detail = (
        f"Paper A: {difference['a']} · Paper B: {difference['b']}" if difference else "no extracted difference"
    )
    rows = [
        (
            "H1",
            f"Differences in {context_field} explain the disagreement",
            f"The papers differ in extracted conditions ({context_detail}); the association may hold in one "
            "context and not the other.",
            "The disagreement survives extraction resampling while clear condition differences are present.",
            "No stable condition difference is extracted, or the disagreement disappears when comparable "
            "claims are re-sampled.",
        ),
        (
            "H2",
            "Methodological or measurement differences explain the disagreement",
            "Different designs or measures can produce different reported effects for the same question.",
            "Extracted design terms differ and statistical reporting coverage is uneven between the papers.",
            "Designs and measures are extracted as equivalent with high statistical coverage in both papers.",
        ),
        (
            "H3",
            "Sampling variability or selective extraction explains the disagreement",
            "An apparent disagreement can be an artifact of which sentences were extracted or chance in small samples.",
            "The disagreement is unstable under claim resampling or disappears when a section is excluded.",
            "A high bootstrap disagreement rate with the top pair stable across section exclusions.",
        ),
    ]
    return [
        Hypothesis(
            hypothesis_id=identifier,
            statement=statement,
            rationale=rationale,
            supporting_evidence=["EV1", "EV2"],
            conflicting_evidence=[],
            predictions=[prediction],
            falsification_condition=falsification,
            uncertainty="Template explanation filled with extracted values; a heuristic, not a probability.",
            agent_generated=False,
            support_score=50,
        )
        for identifier, statement, rationale, prediction, falsification in rows
    ]


def proposals(analysis: dict, seed: int) -> list[Experiment]:
    pairs = analysis.get("pairs") or []
    comparable = sum(1 for p in pairs if p["similarity"] >= 0.18)
    availability = min(1.0, comparable / 5) if pairs else 0.2
    hashes = "+".join(p["id"][:12] for p in analysis["papers"])
    common = dict(
        hypothesis_targets=["H1", "H2", "H3"],
        required_data=f"Uploaded papers / {hashes}",
        variables=((analysis.get("best_pair") or {}).get("shared_terms") or ["shared terms"])[:5],
        feasibility=1,
        data_availability=round(availability, 3),
        computational_cost=0.05,
        limitations=[
            "Operates on extracted text evidence, not the papers' primary data.",
            "Heuristic planning scores, not expected bits of information.",
        ],
        seed=seed,
        bootstrap_samples=300,
        success_criterion=(
            "Disagreement rate ≥ 0.8 across claim resampling with the top pair stable under section exclusion."
        ),
        failure_criterion="The disagreement disappears under resampling or section exclusion.",
    )
    return [
        Experiment(
            experiment_id="E1",
            title="Claim-alignment robustness audit",
            scientific_question="Does the detected disagreement survive resampling of the extracted claims?",
            method="claim_alignment_audit",
            expected_information_gain=0.85,
            discrimination=0.8,
            **common,
        ),
        Experiment(
            experiment_id="E2",
            title="Condition-difference scan",
            scientific_question="How much of the disagreement coincides with extractable condition differences?",
            method="condition_scan",
            expected_information_gain=0.6,
            discrimination=0.55,
            **common,
        ),
    ]


def evaluate(result: dict) -> list[dict]:
    robust = result["robust_disagreement"]
    has_differences = bool(result["condition_differences"])
    coverage = min(result["stats_coverage"]["a"], result["stats_coverage"]["b"])
    if robust and has_differences:
        scores, labels = [75, 55, 25], ["better supported", "remains plausible", "weakened"]
    elif robust:
        scores, labels = [45, 65, 30], ["unresolved", "better supported", "weakened"]
    else:
        scores, labels = [35, 40, 70], ["weakened", "unresolved", "better supported"]
    if coverage < 0.3 and labels[1] != "better supported":
        scores[1], labels[1] = max(scores[1], 60), "deserves attention"
    low, high = result["similarity_ci95"]
    evidence = (
        f"Disagreement rate {result['disagreement_rate']:.2f} over {result['bootstrap_samples']} resamples; "
        f"top-pair similarity 95% CI [{low:.2f}, {high:.2f}]; "
        f"{len(result['condition_differences'])} extracted condition differences; "
        f"section exclusions hold: {all(s['holds'] for s in result['section_sensitivity'])}."
    )
    return [
        {
            "hypothesis_id": f"H{i + 1}",
            "prior_support": 50,
            "updated_support": scores[i],
            "result_consistency": labels[i],
            "evidence_for": evidence,
            "evidence_against": "Text-evidence robustness cannot adjudicate which paper is correct.",
            "remaining_uncertainty": "Scores follow a disclosed heuristic rubric over computed robustness numbers.",
        }
        for i in range(3)
    ]


def critique(result: dict) -> list[dict]:
    top = result["top_pair"]
    low, _ = result["similarity_ci95"]
    sensitivity_holds = all(s["holds"] for s in result["section_sensitivity"])
    from_results = sum(section == "results" for section in (top["section_a"], top["section_b"]))
    sizes = result["sample_sizes"]
    challenges = [
        {
            "challenge_id": "X1",
            "attack": "The headline disagreement is cherry-picked from one section.",
            "test": "Does a disagreement pair survive excluding each section in turn?",
            "evidence": "; ".join(
                f"minus {s['excluded_section']}: {'holds' if s['holds'] else 'gone'} ({s['similarity']:.2f})"
                for s in result["section_sensitivity"]
            )
            + ".",
            "verdict": "rebutted" if sensitivity_holds else "stands",
        },
        {
            "challenge_id": "X2",
            "attack": "The comparison leans on abstracts rather than reported results.",
            "test": "Do the compared claims come from the papers' results sections?",
            "evidence": f"Top pair locations: {top['location_a']} and {top['location_b']}.",
            "verdict": "rebutted" if from_results == 2 else "stands" if from_results == 0 else "open",
        },
        {
            "challenge_id": "X3",
            "attack": "The papers' terminology barely overlaps; they are not comparable.",
            "test": "Is the bootstrap lower bound of top-pair similarity above the comparability floor (0.15)?",
            "evidence": f"Similarity 95% CI lower bound {low:.2f}; shared terms: {', '.join(top['shared_terms'][:5])}.",
            "verdict": "rebutted" if low >= 0.15 else "stands",
        },
        {
            "challenge_id": "X4",
            "attack": "Evidence strength cannot be weighed without sample sizes.",
            "test": "Were sample sizes extracted from both papers?",
            "evidence": f"Extracted n: paper A {sizes['a'] or 'not found'}, paper B {sizes['b'] or 'not found'}.",
            "verdict": "rebutted" if sizes["a"] and sizes["b"] else "open",
        },
        {
            "challenge_id": "X5",
            "attack": "No shared primary dataset was analysed; text evidence cannot settle who is right.",
            "test": "Does a dataset exist in this record covering both papers' conditions?",
            "evidence": "Not tested: this investigation compares extracted claims only.",
            "verdict": "open",
        },
    ]
    for challenge in challenges:
        challenge["challenger"] = "CriticAgent"
        challenge["defender"] = "AnalysisAgent"
    return challenges


def decide(result: dict, updates: list[dict], challenges: list[dict]) -> dict:
    differences = result["condition_differences"]
    context = differences[0]["field"] if differences else "study context"
    topic = result.get("topic") or " ".join(result["top_pair"]["shared_terms"][:3]) or "the shared outcome"
    if result["robust_disagreement"] and differences:
        next_step = f"Design a comparison holding {context} constant"
        reason = (
            "The disagreement is stable under resampling and section exclusion and coincides with extracted "
            f"condition differences; a study varying only {context} would discriminate the explanations."
        )
        search = (
            f"Retrieve studies of {topic} that report both conditions ({differences[0]['a']} vs {differences[0]['b']})."
        )
        next_experiment = f"Obtain or construct comparable primary data on {topic} across {context}"
    elif result["robust_disagreement"]:
        next_step = "Audit methods and measures across the two papers"
        reason = "The disagreement is stable but no extracted condition difference explains it; scrutinise methodology."
        search = f"Retrieve methodological details and instruments used to measure {topic}."
        next_experiment = "Structured methods comparison with full-text measurement details"
    else:
        next_step = "Treat the disagreement as unestablished; replicate the extraction"
        reason = (
            "The disagreement is not robust to claim resampling or section exclusion; it may be an extraction artifact."
        )
        search = f"Retrieve additional studies reporting {topic} to widen the evidence base."
        next_experiment = "Independent re-extraction and a wider literature pull"
    return {
        "previous_plan": "Compare context, methodology and extraction-stability explanations",
        "new_evidence": {
            key: result[key] for key in ("disagreement_rate", "similarity_ci95", "robust_disagreement", "relationship")
        },
        "changed_belief": updates,
        "next_decision": next_step,
        "rationale": reason,
        "next_evidence_search": search,
        "next_experiment": next_experiment,
        "requires_new_approval": True,
        "open_challenges": [c["challenge_id"] for c in challenges if c["verdict"] != "rebutted"],
    }
