import {useEffect,useState} from 'react';
import {ArrowRight,ArrowUpRight,Beaker,Check,ChevronRight,Clock3,Download,FlaskConical,GitBranch,Layers3,Play,Plus,RotateCcw,ShieldCheck,Sparkles,X} from 'lucide-react';
import {objects,type Citation,type Decision,type Evidence,type Experiment,type Hypothesis,type LabObject,type RecordData,type Result,type Update} from './types';
import {Scatter,Slopes} from './Plots';
import {ResearchGraph} from './ResearchGraph';

const stages=['Question','Evidence','Contradiction','Hypotheses','Experiment','Result','Next move'];
const terminal=['complete','failed','no_contradiction','awaiting_approval'];
async function api<T>(path:string,options?:RequestInit):Promise<T>{const r=await fetch('/api'+path,{...options,headers:{'Content-Type':'application/json',...options?.headers}});const body=await r.json();if(!r.ok)throw new Error(typeof body.detail==='string'?body.detail:JSON.stringify(body.detail));return body}
const fmt=(v:unknown)=>typeof v==='number'?v.toFixed(2):String(v??'—');
function Source({citation}:{citation:Citation}){return <a className="source" href={citation.url} target="_blank" rel="noreferrer">Horst, Hill & Gorman · {citation.year}<ArrowUpRight size={13}/></a>}
function Tag({children,tone=''}:{children:React.ReactNode;tone?:string}){return <span className={'tag '+tone}>{children}</span>}

export default function App(){
 const [record,setRecord]=useState<RecordData|null>(null),[ready,setReady]=useState(false),[mode,setMode]=useState('local');
 const [tab,setTab]=useState('Overview'),[error,setError]=useState(''),[busy,setBusy]=useState(false),[modal,setModal]=useState(false),[selected,setSelected]=useState<LabObject|null>(null);
 const [history,setHistory]=useState<{id:string;objective:string;status:string;mode:string}[]>([]),[objective,setObjective]=useState('Why does the relationship between penguin bill length and depth reverse when species are separated?');
 const [chapter,setChapter]=useState(0),[agentsOpen,setAgentsOpen]=useState(false),[switcher,setSwitcher]=useState(false),[search,setSearch]=useState('');
 useEffect(()=>{function escape(e:KeyboardEvent){if(e.key==='Escape'){setAgentsOpen(false);setSwitcher(false);setModal(false);setSelected(null)}}window.addEventListener('keydown',escape);return()=>window.removeEventListener('keydown',escape)},[]);
 useEffect(()=>{if(!modal&&!selected&&!switcher&&!agentsOpen)return;const previous=document.activeElement as HTMLElement;const dialogs=Array.from(document.querySelectorAll<HTMLElement>('[role="dialog"]')).filter(d=>!d.hasAttribute('inert'));const dialog=dialogs.at(-1);if(!dialog)return;const selector='button:not(:disabled),a[href],input,textarea,select,summary,[tabindex="0"]';const controls=()=>Array.from(dialog.querySelectorAll<HTMLElement>(selector)).filter(el=>el.getClientRects().length>0);controls()[0]?.focus();const overflow=document.body.style.overflow;document.body.style.overflow='hidden';function trap(e:KeyboardEvent){if(e.key!=='Tab')return;const elements=controls(),first=elements[0],last=elements.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last?.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first?.focus()}}document.addEventListener('keydown',trap);return()=>{document.removeEventListener('keydown',trap);document.body.style.overflow=overflow;previous?.focus()}},[modal,!!selected,switcher,agentsOpen]);
 useEffect(()=>{window.scrollTo({top:0,behavior:'instant'})},[chapter,tab]);
 const [reference,setReference]=useState<Evidence[]>([]);
 useEffect(()=>{api<{omnigent_ready:boolean}>('/health').then(h=>{setReady(h.omnigent_ready);if(h.omnigent_ready)setMode('omnigent')}).catch(e=>setError(e.message));api<{evidence:Evidence[]}>('/reference').then(r=>setReference(r.evidence)).catch(e=>setError(e.message));refreshHistory()},[]);
 function refreshHistory(){api<typeof history>('/investigations').then(setHistory).catch(e=>setError(e.message))}
 useEffect(()=>{if(!record||record.display_mode==='replay'||terminal.includes(record.status))return;const timer=setInterval(()=>api<RecordData>('/investigations/'+record.id).then(r=>{setRecord(r);if(terminal.includes(r.status))refreshHistory()}).catch(e=>setError(e.message)),700);return()=>clearInterval(timer)},[record?.id,record?.status,record?.display_mode]);
 async function start(){setBusy(true);setError('');try{const r=await api<RecordData>('/investigations',{method:'POST',body:JSON.stringify({objective,mode,seed:42})});setRecord(r);setChapter(1);setTab('Overview');setModal(false);refreshHistory()}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 async function approve(id:string){if(!record)return;setBusy(true);setChapter(5);try{setRecord(await api<RecordData>(`/investigations/${record.id}/approve`,{method:'POST',body:JSON.stringify({experiment_id:id,approved:true})}))}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 async function load(id:string,replay=false){setError('');try{setRecord(await api<RecordData>(`/investigations/${id}${replay?'/replay':''}`));setTab('Overview');setChapter(0);setSwitcher(false)}catch(e){setError((e as Error).message)}}
 const evidence=record?objects<Evidence>(record,'evidence'):reference,hypotheses=objects<Hypothesis>(record,'hypothesis'),experiments=objects<Experiment>(record,'experiment'),result=objects<Result>(record,'result')[0],updates=objects<{updates:Update[]}>(record,'analysis')[0]?.updates,decision=objects<Decision>(record,'decision')[0];
 const stage=record?record.stage>=7?6:record.stage>=5?5:record.stage>=4?4:record.stage:0;
 const status=record?.display_mode==='replay'?'Verified replay':record?.status.replaceAll('_',' ')||'Ready to investigate';
 const findObject=(kind:string)=>{const o=Object.values(record?.objects||{}).find(o=>o.kind===kind);if(o)setSelected(o)};
 return <div className="app-shell">
  <aside className="sidebar"><a className="brand-icon" href="/" aria-label="Contradiction Lab"><FlaskConical size={25}/></a><div className="rail-nav">{[{name:'Overview',label:'Investigation',icon:Layers3},{name:'Research graph',label:'Research graph',icon:GitBranch},{name:'Lab notebook',label:'Lab notebook',icon:Beaker}].map(({name,label,icon:Icon})=><button key={name} title={label} aria-label={name} className={'nav-item '+(tab===name?'active':'')} onClick={()=>setTab(name)}><Icon size={21}/></button>)}</div><ShieldCheck className="rail-status" size={20}/></aside>
  <div className={'main-shell '+(chapter>0||tab!=='Overview'?'focused':'opening')}><header className="topbar"><a href="/" className="wordmark">contradiction<span>lab</span></a><button className="workspace-switch" onClick={()=>setSwitcher(true)}>Scientific workspace <ChevronRight size={15}/></button><button className="text-button" onClick={()=>setModal(true)}><Plus size={16}/>New investigation</button></header>
  <div className="page-intro"><div><div className="eyebrow">INVESTIGATION <span>/</span> PENGUIN MORPHOLOGY</div><h1>Same evidence. Opposite conclusions.</h1><p>{record?.objective||objective}</p></div><div className="intro-actions">{record?.status==='complete'&&<button className="button" onClick={()=>load(record.id,true)}><RotateCcw size={15}/>Replay verified run</button>}<button className="button primary" onClick={()=>record?setModal(true):start()} disabled={busy}><Play size={15}/>{busy?'Starting…':'Run investigation'}</button></div></div>
  <div className={'mode-strip '+(record?.display_mode==='replay'?'replay':'')}><span><i className="status-dot"/>{record?.display_mode==='replay'?'REPLAY VERIFIED RUN':(record?.mode||mode)==='omnigent'?'LIVE · OMNIGENT ORCHESTRATION':'LOCAL DEVELOPMENT · REAL COMPUTATION'}</span><span>{record?.display_mode==='replay'?'Persisted execution · checksum verified':(record?.mode||mode)==='local'?'Deterministic specialists · no LLM / no Omnigent claim':'Official Omnigent specialist workflow'}</span></div>
  {error&&<div className="error" role="alert">{error}<button aria-label="Dismiss error" onClick={()=>setError('')}><X size={16}/></button></div>}{record?.error&&<div className="error" role="alert">{record.error}</div>}
  <nav className="progress-rail" aria-label="Investigation stages">{stages.map((s,i)=><button key={s} aria-current={chapter===i&&tab==='Overview'?'step':undefined} className={(record&&(i<stage||record.status==='complete')?'done ':'')+(i===chapter&&tab==='Overview'?'current':'')} onClick={()=>{setTab('Overview');setChapter(i)}}><span className="step-number">{record&&(i<stage||record.status==='complete')?<Check size={18}/>:String(i+1).padStart(2,'0')}</span><span>{s}</span>{i===4&&record?.status==='awaiting_approval'&&<span className="approval-ready">Approval ready</span>}</button>)}</nav>
  <div className="workspace-grid"><main className="content">
  {tab==='Overview'&&<div className={'chapter chapter-'+chapter} key={chapter}>
   {chapter===0&&<section className="question-card" id="stage-0"><div className="section-kicker"><span className="eyebrow">RESEARCH QUESTION / 01</span><Tag tone="green">{status}</Tag></div><h2>{record?.objective||objective}</h2><div className="question-meta"><span><Layers3 size={13}/>Palmer Penguins</span><span><Clock3 size={13}/>2007–2009 observations</span><span><ShieldCheck size={13}/>CC0 · public data</span></div><p className="scope-note">Reference reanalysis of a published aggregation reversal. One article, two analysis contexts; not conflicting independent studies.</p><button className="button primary begin" disabled={busy} onClick={()=>record?setChapter(1):start()}>Begin investigation<ArrowRight size={18}/></button></section>}
   {chapter===1&&<section id="stage-1"><div className="section-heading"><div><span className="eyebrow">02 / SOURCE EVIDENCE</span><h2>A contradiction hiding in plain sight</h2></div><Tag>1 source · 2 contexts</Tag></div><div className="evidence-grid">{evidence.map((e,i)=><article className={'evidence-card '+(i===0?'negative':'positive')} key={e.evidence_id}><div className="card-top"><span className="eyebrow">{i===0?'A / POOLED ANALYSIS':'B / WITHIN-SPECIES ANALYSIS'}</span><Tag>{i===0?'Negative':'Positive'} association</Tag></div><h3>{i===0?'Longer bills, shallower depth.':'Longer bills, greater depth.'}</h3><p>{e.claim}</p><dl>{Object.entries(e.experimental_conditions).map(([k,v])=><div key={k}><dt>{k}</dt><dd>{v}</dd></div>)}</dl><Source citation={e.citation}/><details><summary>Source details & limitations</summary><p>{e.citation.title}</p><p>{e.citation.location}</p>{e.limitations.map(l=><p key={l}>{l}</p>)}</details></article>)}</div><div className="conflict-band"><span className="conflict-symbol">≠</span><div><strong>Same measurements. Opposite associations.</strong><p>One published source, two analysis contexts.</p></div><button className="text-button" onClick={()=>setChapter(2)}>Explore the contradiction<ArrowRight size={18}/></button></div></section>}
   {chapter===2&&<section id="stage-2"><div className="section-heading"><div><span className="eyebrow">03 / THE CONTRADICTION</span><h2>Perspective changes everything.</h2></div><button className="text-button" onClick={()=>findObject('contradiction')} disabled={!record||record.stage<2}>Trace evidence<ArrowUpRight size={16}/></button></div><div className="opposing"><div><span className="eyebrow">AGGREGATED DATA</span><h3 className="coral">↘ Negative relationship</h3></div><span>≠</span><div><span className="eyebrow">WITHIN SPECIES</span><h3 className="mint">↗ Positive relationship</h3></div></div>{result?<Scatter result={result}/>:<div className="contradiction-explainer"><span className="editorial-mark">≠</span><h3>The species context changes.<br/>The measurements do not.</h3><p>The source reports an aggregation reversal. Run an experiment to explore the measured birds and fitted trends.</p></div>}<button className="button primary" onClick={()=>setChapter(3)}>Explore hypotheses<ArrowRight size={18}/></button></section>}
   {chapter===3&&<section id="stage-3"><div className="section-heading"><div><span className="eyebrow">04 / COMPETING EXPLANATIONS</span><h2>Three explanations.<br/>One contradiction.</h2></div><span className="muted">Support scores ≠ probabilities</span></div>{hypotheses.length?<div className="hypothesis-grid">{hypotheses.map((h,i)=>{const u=updates?.find(u=>u.hypothesis_id===h.hypothesis_id);return <article className="hypothesis-card" key={h.hypothesis_id}><div className="card-top"><span className="hypothesis-id">{h.hypothesis_id}</span><Tag>{h.agent_generated?'AI-generated candidate':'Reference candidate'}</Tag></div><h3>{h.statement}</h3><div className="score-line"><span>Agent support · heuristic</span><strong>{u?.updated_support??h.support_score}<small>/100</small></strong></div><div className="score-track"><div style={{width:`${u?.updated_support??h.support_score}%`}}/></div>{u&&<div className="update-label">{u.prior_support} → {u.updated_support} · {u.result_consistency}</div>}<details><summary>Prediction & falsification</summary><h4>PREDICTION</h4>{h.predictions.map(p=><p key={p}>{p}</p>)}<h4>WEAKENED IF</h4><p>{h.falsification_condition}</p><h4>RATIONALE</h4><p>{h.rationale}</p></details></article>})}</div>:<Empty text="Start the investigation to register testable explanations."/>}</section>}
   {chapter===4&&<section id="stage-4"><div className="section-heading"><div><span className="eyebrow">05 / EXPERIMENT DESIGN</span><h2>Choose the test that teaches us more</h2></div><Tag>Human approval required</Tag></div>{experiments.length?<><div className="experiment-grid">{experiments.map(e=><article className={'experiment-card '+(e.experiment_id===record?.selected_experiment?'recommended':'')} key={e.experiment_id}><div className="card-top"><span className="eyebrow">{e.experiment_id} / COMPUTATIONAL EXPERIMENT</span>{e.experiment_id===record?.selected_experiment&&<Tag tone="green">Selected by planner</Tag>}</div><h3>{e.method==='species_adjustment'?'Species-adjusted regression':'Year-adjusted sensitivity'}</h3><p>{e.scientific_question}</p><div className="planning-metrics">{[['Learning value',e.expected_information_gain],['Feasibility',e.feasibility],['Data coverage',e.data_availability],['Planning score',e.planning_score]].map(([k,v])=><div key={k}><span>{k}</span><strong>{Math.round(Number(v)*100)}<small>/100</small></strong><meter min="0" max="1" value={Number(v)} aria-label={String(k)}/></div>)}</div><details><summary>Planning assumptions & cost</summary><p className="caption">Discrimination: {Math.round(e.discrimination*100)} / 100 · Compute cost: {e.computational_cost}</p>{e.limitations.map(l=><p className="caption" key={l}>{l}</p>)}</details><p className="caption">{e.bootstrap_samples} bootstrap samples · seed {e.seed} · local CPU<br/>Observational, exploratory; no causal identification.</p>{record?.status==='awaiting_approval'&&record.display_mode!=='replay'&&<button className={'button full '+(e.experiment_id===record.selected_experiment?'primary':'')} disabled={busy} onClick={()=>approve(e.experiment_id)}><ShieldCheck size={16}/>{e.experiment_id===record.selected_experiment?'Approve & run experiment':'Approve alternative & run'}</button>}</article>)}</div><div className="rationale"><Sparkles size={16}/><p><strong>Why this experiment?</strong> {record?.selection_rationale}</p></div></>:<Empty text="The planner will compare learning value, feasibility, data coverage and compute cost."/>}</section>}
   {chapter===5&&<section id="stage-5"><div className="section-heading"><div><span className="eyebrow">06 / COMPUTATIONAL EVIDENCE</span><h2>{result?(result.pooled_slope*result.adjusted_slope<0?'The relationship reverses.':'The evidence is in.'):'Run the experiment. Follow the evidence.'}</h2></div>{result&&<Tag tone="green">Actual result · n = {result.n}</Tag>}</div>{result?<><div className="result-metrics"><div><span>Pooled slope</span><strong className="coral">{result.pooled_slope.toFixed(3)}</strong><small>mm / mm</small></div><ArrowRight size={23}/><div><span>{result.group}-adjusted slope</span><strong className="mint">{result.adjusted_slope>0?'+':''}{result.adjusted_slope.toFixed(3)}</strong><small>mm / mm</small></div><div><span>95% bootstrap interval</span><strong className="interval">[{result.adjusted_ci95.map(v=>v.toFixed(3)).join(', ')}]</strong><small>{result.bootstrap_samples} stratified draws · seed {result.seed}</small></div></div><div className="support-updates">{updates?.map(u=><div key={u.hypothesis_id}><span>{u.hypothesis_id} · agent support / 100</span><strong>{u.prior_support} → {u.updated_support}</strong><p>{u.result_consistency}</p></div>)}</div><details className="details"><summary>Explore measured data & regression slopes</summary><Scatter result={result}/><Slopes result={result}/></details><details className="details"><summary>Assumptions, sensitivity & reproducibility</summary><p>In-sample RMSE: {result.pooled_rmse.toFixed(3)} pooled → {result.adjusted_rmse.toFixed(3)} adjusted.</p><div className="sensitivity">{result.sensitivity.map(s=><span key={s.excluded_year}>Omit {s.excluded_year}: <strong>{s.slope.toFixed(3)}</strong></span>)}</div>{[...result.assumptions,...result.limitations].map(v=><p key={v}>• {v}</p>)}<p className="hash">Dataset SHA-256: {result.provenance.dataset_sha256}</p><p className="hash">Code SHA-256: {result.provenance.code_sha256}</p><button className="text-button" onClick={()=>findObject('result')}>Inspect complete result provenance<ArrowUpRight size={14}/></button></details></>:record?.status==='running'?<div className="running" role="status"><div className="spinner"/><span className="eyebrow">LIVE EXPERIMENT EXECUTION</span><h3>Following the evidence.</h3><p>{record.events.at(-1)?.action}</p><div className="execution-events">{record.events.filter(e=>e.agent==='ExperimentRunner'||e.status==='running').map(e=><p key={e.id}>{e.status==='running'?'◉':'✓'} {e.action}</p>)}</div></div>:<Empty text="Approval launches regression, resampling, sensitivity checks and artifact persistence."/>}</section>}
   {chapter===6&&<section id="stage-6"><div className="section-heading"><div><span className="eyebrow">07 / EVIDENCE-DRIVEN DECISION</span><h2>Science moves when the plan changes.</h2></div><GitBranch size={21}/></div>{decision?<div className="decision-card"><div className="decision-columns"><div><span className="eyebrow">BEFORE THE EXPERIMENT</span><h3>{decision.previous_plan}</h3><p>Three plausible explanations. Neutral initial support.</p></div><div className="decision-arrow"><ArrowRight size={25}/></div><div><span className="eyebrow mint">AFTER THE EXPERIMENT</span><h3>{decision.next_decision}</h3><p>{decision.rationale}</p></div></div><div className="next-test"><Beaker size={20}/><div><span className="eyebrow">NEXT SCIENTIFIC ACTION</span><strong>{decision.next_experiment}</strong><p>{decision.next_evidence_search}</p></div><button className="button" onClick={()=>{setObjective(decision.next_experiment);setModal(true)}}>Continue discovery<ArrowRight size={16}/></button></div></div>:<Empty text="The next decision will be selected from the actual result, after uncertainty and sensitivity checks."/>}</section>}
   <div className="chapter-footer"><span>FIELD NOTES / {String(chapter+1).padStart(2,'0')} — 07</span>{chapter>0&&<button className="text-button" onClick={()=>setChapter(chapter-1)}>Previous chapter</button>}{chapter<6&&<button className="text-button" onClick={()=>setChapter(chapter+1)}>{stages[chapter+1]}<ArrowRight size={17}/></button>}</div>
  </div>}
  {tab==='Research graph'&&<section><div className="section-heading"><div><span className="eyebrow">CONNECTED RESEARCH RECORD</span><h2>Follow the evidence backward.</h2></div></div><p className="muted">Select a node to inspect its inputs, scientific data and provenance.</p>{record?<ResearchGraph record={record} onSelect={setSelected}/>:<Empty text="Start an investigation to build its provenance graph."/>}</section>}
  {tab==='Lab notebook'&&<section><div className="section-heading"><div><span className="eyebrow">PERSISTENT & RECONSTRUCTABLE</span><h2>Lab notebook</h2></div>{record&&<a className="button" href={`/api/investigations/${record.id}/export`}><Download size={15}/>Export JSON</a>}</div><p className="muted">Observable actions and scientific rationale only. Every handoff retains stable object IDs.</p>{!record&&<Empty text="Start an investigation to begin the research notebook."/>}{record&&<details className="details"><summary>Discovery measurements</summary><div className="support-updates">{Object.entries(record.metrics).map(([key,value])=><div key={key}><span>{key.replaceAll('_',' ')}</span><p>{typeof value==='number'?fmt(value):value}</p></div>)}</div><p className="caption">Measured prototype activity. No manual baseline or speedup claim. Wall time includes human approval.</p></details>}{record?.events.map(e=><article className="notebook-event" key={e.id}><div><Tag>{e.agent}</Tag><span className="muted">{new Date(e.timestamp).toLocaleTimeString()}</span></div><h3>{e.action}</h3><p>Tool: <code>{e.tool}</code> · {e.elapsed_seconds.toFixed(3)}s</p><div className="id-links">{[...e.input_ids,...e.output_ids].map(id=><button key={id} onClick={()=>setSelected(record.objects[id])}>{id}<ArrowUpRight size={12}/></button>)}</div></article>)}</section>}
  <footer>Contradiction Lab <span>Evidence → Experiment → Updated decision</span><a href="https://journal.r-project.org/articles/RJ-2022-020/" target="_blank" rel="noreferrer">Reference science<ArrowUpRight size={12}/></a></footer>
  </main>{agentsOpen&&<div className="drawer-backdrop" onClick={()=>setAgentsOpen(false)}/>}<aside className={"agent-panel "+(agentsOpen?"open":"")} role="dialog" aria-modal={agentsOpen} aria-label="Agent activity" inert={!agentsOpen}><div className="agent-panel-heading"><span className="eyebrow">{(record?.mode||mode)==='omnigent'?'OMNIGENT':'LOCAL SPECIALISTS'} / ORCHESTRATION</span><button aria-label="Close agents" onClick={()=>setAgentsOpen(false)}><X size={20}/></button></div><h3>Observable work.<br/>Traceable decisions.</h3><p className="agent-disclosure">{(record?.mode||mode)==='local'?'Local mode runs deterministic specialist tools. Activity below comes from real backend events.':'Omnigent routes specialist agents through restricted scientific tools.'}</p><div className="activity-list">{record?.events.length?record.events.map((e,i)=><div className="activity" key={e.id}><div className="activity-icon">{e.agent==='Human'?<ShieldCheck size={14}/>:e.status==='running'?<Clock3 size={13}/>:<Check size={13}/>}</div><div><div className="activity-title">{e.agent.replace('Agent','')}<span>{i+1<10?'0':''}{i+1}</span></div><p>{e.action}</p><details><summary>Inspect handoff</summary><small>Tool: {e.tool} · {e.elapsed_seconds.toFixed(2)}s</small><p>Input: {e.input_ids.join(', ')||'Objective'}</p><p>Output: {e.output_ids.join(', ')||'Pending'}</p></details>{e.output_ids.length>0&&<button className="trace" onClick={()=>setSelected(record.objects[e.output_ids[0]])}>Inspect output<ArrowUpRight size={11}/></button>}</div></div>):<div className="agent-empty"><FlaskConical size={27}/><p>The lab is ready.</p><small>Start the demo to see evidence retrieval, scientific tools and structured handoffs.</small></div>}</div><div className="rigor-box"><ShieldCheck size={18}/><strong>Rigor is part of the workflow.</strong><p>Citations. Explicit uncertainty. Human approval. Reproducible computation.</p></div></aside></div></div><button className={"agents-trigger "+(record&&!terminal.includes(record.status)?"working":"")} onClick={()=>setAgentsOpen(!agentsOpen)} aria-expanded={agentsOpen}><span className="live-dot"/>Agents <span>{record?.events.length||0}</span></button>
  {switcher&&<div className="modal-backdrop" onClick={()=>setSwitcher(false)}><div className="modal switcher" role="dialog" aria-modal="true" aria-labelledby="workspace-title" onClick={e=>e.stopPropagation()}><button className="close" aria-label="Close workspace" onClick={()=>setSwitcher(false)}><X size={20}/></button><span className="eyebrow">YOUR RESEARCH</span><h2 id="workspace-title">Investigations</h2><input autoFocus aria-label="Search investigations" placeholder="Find a scientific question…" value={search} onChange={e=>setSearch(e.target.value)}/><div className="history">{history.filter(h=>h.objective.toLowerCase().includes(search.toLowerCase())).map(h=><button key={h.id} onClick={()=>load(h.id)}><span className={'status-dot '+h.status}/><span>{h.objective}<small>{h.id.slice(-6)} · {h.status.replaceAll('_',' ')}</small></span><ArrowUpRight size={18}/></button>)}</div><button className="button" onClick={()=>{setSwitcher(false);setModal(true)}}><Plus size={17}/>New investigation</button></div></div>}
  {modal&&<div className="modal-backdrop" onClick={()=>setModal(false)}><div className="modal" role="dialog" aria-modal="true" aria-labelledby="modal-title" onClick={e=>e.stopPropagation()}><button className="close" aria-label="Close" onClick={()=>setModal(false)}><X size={20}/></button><span className="eyebrow">NEW INVESTIGATION</span><h2 id="modal-title">Set the scientific objective.</h2><p>Reference investigation: Palmer Penguins. The objective guides interpretation; this prototype keeps the dataset and scientific tools fixed.</p><label htmlFor="objective">Research objective</label><textarea id="objective" value={objective} onChange={e=>setObjective(e.target.value)} maxLength={600}/><label htmlFor="engine">Execution engine</label><select id="engine" value={mode} onChange={e=>setMode(e.target.value)}><option value="local">Local development — real computation, deterministic tools</option><option value="omnigent" disabled={!ready}>Omnigent — live specialist agents{!ready?' (credentials required)':''}</option></select>{!ready&&<p className="caption">Sponsor mode needs Omnigent 0.16.0 and OPENAI_API_KEY on the backend. No silent fallback.</p>}<button className="button primary full" disabled={busy||objective.length<10} onClick={start}><Play size={15}/>Start investigation</button></div></div>}
  {selected&&<div className="modal-backdrop" onClick={()=>setSelected(null)}><div className="modal provenance-modal" role="dialog" aria-modal="true" aria-labelledby="provenance-title" onClick={e=>e.stopPropagation()}><button className="close" aria-label="Close provenance" onClick={()=>setSelected(null)}><X size={20}/></button><span className="eyebrow">RESEARCH RECORD / {selected.kind.toUpperCase()}</span><h2 id="provenance-title">{selected.id}</h2><p>Created {new Date(selected.created_at).toLocaleString()}</p><h4>DERIVED FROM</h4><div className="id-links">{selected.input_ids.length?selected.input_ids.map(id=><button key={id} onClick={()=>setSelected(record?.objects[id]||null)}>{id}<ArrowUpRight size={12}/></button>):<span className="muted">Human scientific objective</span>}</div><pre>{JSON.stringify(selected.data,null,2)}</pre></div></div>}
 </div>
}
function Empty({text}:{text:string}){return <div className="empty-state"><Beaker size={20}/><p>{text}</p></div>}
